# Generated by Django 4.0.1 on 2022-01-11 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('model', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rangli', models.BooleanField()),
                ('narx', models.IntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Computer.product')),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RAM', models.SmallIntegerField()),
                ('HD', models.SmallIntegerField()),
                ('narx', models.IntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Computer.product')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RAM', models.SmallIntegerField()),
                ('HD', models.SmallIntegerField()),
                ('narx', models.IntegerField()),
                ('ekran', models.CharField(max_length=10)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Computer.product')),
            ],
        ),
    ]
